sudo: required
dist: trusty

language: cpp
compiler: gcc

matrix:
  include:
    - env: NAME="clang-format"
      sudo: false
      dist: precise
      language: generic
      compiler:
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - clang-format-3.8

    - env: NAME="gcc-4.8"

    # works on Precise and Trusty
    - addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env:
        - NAME="gcc-6.3"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - compiler: clang
      env: NAME="clang-3.9"

    - os: osx
      osx_image: xcode8
      compiler:
      env: NAME="xcode-8.3"

install: $TRAVIS_BUILD_DIR/scripts/travis/install.sh

script: $TRAVIS_BUILD_DIR/scripts/travis/script.sh

after_success: $TRAVIS_BUILD_DIR/scripts/travis/after_success.sh

deploy:
  - provider: releases
    file:
      - linux-xtalopt.tgz
      - linux-xtalopt.md5
    skip_cleanup: true
    api_key:
      secure: OV+fiXKG9XW6AHN2p79aFdIiGbkf6ofatJ0QWLzOhtAylrUmKL2rdaQLve64g7DXdzDMuUKXLncXPYdIoPLYau9CvZvejNhGCKH+GDRuUuW1TbivRHEBQvxZCGqH5YGKTRLu8Ip7RNeQo0+3KWT6aed971NVzPV2zgET1okSvDFTJIC+ZyZ6gd2u0WeKPerVgZk9RgF7liIykJnL74mi51IRDslKNNsyXC2fEDwRqCBpO6E2QpxSHnTKmMLy1jdfI+V1bEyqi3Bfc8lRuzbUh5YpxZ0GQlzjWqLosAaIVy07YON3UcPQz6aiXr0PGUXknVLwK2y2Vdo2LV3KGo9o5ahyU2roXThVCyhVRPyYKU+4PdXJPeH3dmOmc25keF9ubWhgvWCExacue7g1ww4cN+yKHAJJOlsHyIaDhS/F72nKad4YVSpLpw0pY29qY8yrEHGYW2YbIP70UL2r70KIBFvsaBBbIrl0N5CnRsmbZkGi0urXgYttfw/ehhgPkDgueONjnGHgqbPSHQ0JpxlOWSy8ghjhYpXTDVaUp54uWZfN7OnqufN5rkCoWA5Q6Qkh8PbiOPNb9IMuzkP1wlxYtVI43vUekeS7+RVtXnowrKb1z/19kCeZrvKuVM18achHwM6uXMbn6IjQLHJqpn21n8tca+6gyWDZGiuYzkceHhQ=
    on:
      repo: xtalopt/XtalOpt
      tags: true
      all_branches: true
      condition: $NAME = "gcc-4.8"

  - provider: releases
    file:
      - osx-xtalopt.zip
      - osx-xtalopt.md5
    skip_cleanup: true
    api_key:
      secure: OV+fiXKG9XW6AHN2p79aFdIiGbkf6ofatJ0QWLzOhtAylrUmKL2rdaQLve64g7DXdzDMuUKXLncXPYdIoPLYau9CvZvejNhGCKH+GDRuUuW1TbivRHEBQvxZCGqH5YGKTRLu8Ip7RNeQo0+3KWT6aed971NVzPV2zgET1okSvDFTJIC+ZyZ6gd2u0WeKPerVgZk9RgF7liIykJnL74mi51IRDslKNNsyXC2fEDwRqCBpO6E2QpxSHnTKmMLy1jdfI+V1bEyqi3Bfc8lRuzbUh5YpxZ0GQlzjWqLosAaIVy07YON3UcPQz6aiXr0PGUXknVLwK2y2Vdo2LV3KGo9o5ahyU2roXThVCyhVRPyYKU+4PdXJPeH3dmOmc25keF9ubWhgvWCExacue7g1ww4cN+yKHAJJOlsHyIaDhS/F72nKad4YVSpLpw0pY29qY8yrEHGYW2YbIP70UL2r70KIBFvsaBBbIrl0N5CnRsmbZkGi0urXgYttfw/ehhgPkDgueONjnGHgqbPSHQ0JpxlOWSy8ghjhYpXTDVaUp54uWZfN7OnqufN5rkCoWA5Q6Qkh8PbiOPNb9IMuzkP1wlxYtVI43vUekeS7+RVtXnowrKb1z/19kCeZrvKuVM18achHwM6uXMbn6IjQLHJqpn21n8tca+6gyWDZGiuYzkceHhQ=
    on:
      repo: xtalopt/XtalOpt
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = "osx"
